services:
  cra-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta do CRA no container para o host
    volumes:
      - .:/app # Mapeia o diretório local para o container
      - /app/node_modules # Ignora a sincronização do node_modules
    command: npm start